/* 🚨🚨🚨 THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. 🚨🚨🚨 */
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>;
};
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>;
};
export type MakeEmpty<
  T extends { [key: string]: unknown },
  K extends keyof T,
> = { [_ in K]?: never };
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never;
    };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
  Date: { input: any; output: any };
  JSONObject: { input: any; output: any };
  Upload: { input: any; output: any };
};

export class Animal {
  __typename?: "Animal";
  name: Scalars["String"]["output"];
}

export class AnimalsAndPokemonResponse {
  __typename?: "AnimalsAndPokemonResponse";
  animals: Array<Animal>;
  pokemon: Array<Pokemon>;
}

export class Mutation {
  __typename?: "Mutation";
  do: Sample;
}

export class Pokemon {
  __typename?: "Pokemon";
  name: Scalars["String"]["output"];
  url: Scalars["String"]["output"];
}

export class Query {
  __typename?: "Query";
  animals: Array<Animal>;
  animalsAndPokemon?: Maybe<AnimalsAndPokemonResponse>;
  pokemon: Array<Pokemon>;
  sample: Sample;
  token?: Maybe<Scalars["String"]["output"]>;
  tokenLong?: Maybe<Scalars["String"]["output"]>;
}

export class SNSMessage {
  __typename?: "SNSMessage";
  message?: Maybe<Scalars["String"]["output"]>;
  messageId?: Maybe<Scalars["String"]["output"]>;
  signature?: Maybe<Scalars["String"]["output"]>;
  signatureVersion?: Maybe<Scalars["String"]["output"]>;
  signingCertUrl?: Maybe<Scalars["String"]["output"]>;
  subject?: Maybe<Scalars["String"]["output"]>;
  timestamp?: Maybe<Scalars["String"]["output"]>;
  topicArn?: Maybe<Scalars["String"]["output"]>;
  type?: Maybe<Scalars["String"]["output"]>;
  unsubscribeUrl?: Maybe<Scalars["String"]["output"]>;
}

export class Sample {
  __typename?: "Sample";
  id: Scalars["ID"]["output"];
  name: Scalars["String"]["output"];
  now: Scalars["Date"]["output"];
  test?: Maybe<Scalars["String"]["output"]>;
}
