extend type Query {
  animals: [Animal!]!
  animalsAndPokemon: AnimalsAndPokemonResponse
}

type AnimalsAndPokemonResponse {
  animals: [Animal!]!
  pokemon: [Pokemon!]!
}

type Animal {
  name: String!
}
